### ISSUE TITLE
Base model completions API

### ISSUE THREAD

**Issue by satin-spirit** [restlessronin/openai_ex#102]
### Describe the feature or improvement you're requesting

README.md states that:

> 3rd Party LLMs with an OpenAI proxy ... are considered legitimate use cases.

Yet the ability to use the `/completions` API was removed in 312f502, making the library unusable for base model completions. To me, this seems counterintuitive: many providers (for example, TogetherAI) require the use of `/completions` for base models. I don't think the library should consider the `/completions` API deprecated, as it is well within the scope of third-party providers.

**Comment by restlessronin** [comment]
@satin-spirit My apologies. I don't use it myself, and wasn't aware others were still using the API. Feel free to add it back in with a PR, and I will accept it. I can't test it out myself, so it would be great if you could check that it works on the 3rd party servers that you care about.

**Comment by satin-spirit** [comment]
No problem. Thank you for the quick reply ^^
