### ISSUE TITLE
Tesla warning on every request.

### ISSUE THREAD

**Issue by restlessronin** [restlessronin/openai_ex#40]
### Describe the bug

```
[warn] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
```

### To Reproduce

Any openai call in a livebook

### OS

macOs

### Elixir version

Elixir 1.14.2

### Library version

openai_ex v0.1.6

**Comment by restlessronin** [comment]
It may actually be simpler to replace Tesla with Finch than to fix the warning.

**Comment by restlessronin** [comment]
Waiting on response to https://github.com/breakroom/multipart/issues/14

**Comment by teamon** [comment]
Just FYI, the warning is due to using the default built-in httpc adapter (which does not handle ssl properly) instead of a good one like hackney/mint/finch - https://github.com/elixir-tesla/tesla#installation

**Comment by restlessronin** [comment]
Thanks. I was trying to use hackney at that point (https://hex.pm/packages/openai_ex/0.1.2), but I must have made a mistake with the configuration. At the moment, the library is using Finch with streaming completions, and I don't want to switch again until there's a clear need.

But this is useful to know. I think I've seen this warning in some of my private projects that use Tesla, so I can fix those.

Thanks.
