### ISSUE TITLE
Add functions to the chat_completion api_fields list

### ISSUE THREAD

**Issue by TomBers** [restlessronin/openai_ex#53]
### Describe the feature or improvement you're requesting

I wanted to use your Lib to try out the function calling with the chat completions api (outlined here - https://platform.openai.com/docs/guides/gpt/function-calling) it is a simple change just adding :functions & :function_call params to the @api_fields list in `lib/openai_ex/chat_completion.ex`.  I have the change on a local branch and have tested it works as expected (the API returns the name and params of a function to be called, see additional context.)

Great work on the lib, it works really well. 

### Additional context

<img width="857" alt="image" src="https://github.com/restlessronin/openai_ex/assets/1389427/8e477660-810d-43af-bd1b-f90e91e16724">

**Comment by restlessronin** [comment]
@TomBers Nice timing! I just noticed that additional functionality yesterday and was going to update the library to the latest API version over the weekend.

It's a small change, but in the spirit of recognizing contribution, I'd be happy to take your PR if it's ready. It would be useful if you could add an example to the user guide as well.

**Comment by restlessronin** [comment]
@TomBers please let me know if you would like to contribute your PR. Otherwise, I'll go ahead and make the updates myself. In any case, I will go through the latest specs and add any other new functionality / drop any deprecated functionality. I will likely do a new minor release right after.

**Comment by TomBers** [comment]
@restlessronin thanks for getting back to me.  I am happy to push what I did, if you are happy to give me permission.

**Comment by restlessronin** [comment]
@TomBers Did you fork the repo? It's not showing up on the list of forks. AFAIK, you should be able to do a Pull Request from your fork to the upstream repository (my repo) without requiring any explicit permission.

**Comment by restlessronin** [comment]
@TomBers I'm already most of the way through doing the updates, but I will try to merge your changes or figure out a way to credit you as a contributor.

**Comment by TomBers** [comment]
Np, at this point it makes more sense for you to do it.  Happy to help.

**Comment by TomBers** [comment]
P.s, thanks for the quick response, I really appreciate the work you have done for this and found the code very intuitive when I was reading it.  All the best.

**Comment by restlessronin** [comment]
@TomBers I have added function calling as well as synced up in other ways to the latest version of the spec. I added you as a coauthor on one file change. It's not exactly the right file, but it took me a while to figure out how to add a coauthor using my regular (non command line) tooling. 🎉

Have bumped the library to 0.3.0.

Thanks for the timely feedback and your appreciation 🙏🏾🙏🏾🙏🏾.
