### ISSUE TITLE
Add Azure OpenAI Support

### ISSUE THREAD

**Issue by restlessronin** [restlessronin/openai_ex#80]
### Describe the feature or improvement you're requesting

Discussion on how adding azure support [starting at this message](https://elixirforum.com/t/openai-ex-openai-api-client-library/55353/76?u=restlessronin).

**Comment by restlessronin** [comment]
Apparently the MS Entra Id route is cumbersome. I've made another change to support the non-Entra-Id case. The openai value needs to be created as follows

```elixir
def for_azure(azure_api_key) do
%OpenaiEx{
_http_headers: [{"api-key", "#{azure_api_key}"}]
}
end
```
then the path map has to be attached
```
azure_openai = for_azure(azure_key) |> OpenaiEx._with_ep_path_mapping(&azure_ep_path_map/1)
```
Please see if this works for you.

**Comment by restlessronin** [comment]
I have added what I believe to be the support functions needed for azure. The user only needs to call a single function for Azure. For non entra-id, you need to do
```elixir
openai = OpenaiEx._for_azure(azure_api_id, resource_name, deployment_id, api_version)
```
for Entra Id it becomes
```elixir
openai = OpenaiEx.new(entra_id) |> OpenaiEx._for_azure(resource_name, deployment_id, api_version)
```
and then use the rest of the API as is.

This is only applicable for the "/completions", "/chat/completions" and "/embeddings" end points.

**Comment by restlessronin** [comment]
@raulchedrese Since this branch is based on your fixes and references, I would like to give you co-author credit on a commit. Would that be OK?

**Comment by raulchedrese** [comment]
👍🏽 sure. Thanks for adding this!
